"""Add fs_uniquifier to User

Revision ID: 66b8575f06d7
Revises: 7eaab9f89350
Create Date: 2023-08-12 00:54:19.752120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b8575f06d7'
down_revision = '7eaab9f89350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_fs_uniquifier'), ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_fs_uniquifier'), type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
