"""DB booking showtime changes

Revision ID: e23b78e77f6b
Revises: f8c3f849c44d
Create Date: 2023-04-09 17:54:46.681293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23b78e77f6b'
down_revision = 'f8c3f849c44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showTime', sa.String(length=255), nullable=False))
        batch_op.drop_column('show')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('show_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_time', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('showTime')

    # ### end Alembic commands ###
