"""DB booking changes

Revision ID: f8c3f849c44d
Revises: e7b3a39fc122
Create Date: 2023-04-09 17:33:08.288862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c3f849c44d'
down_revision = 'e7b3a39fc122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('show_time')

    # ### end Alembic commands ###
